services:
  htoj-dev:
    container_name: htoj-dev
    image: htoj-dev:latest
    build: .
    volumes:
      - ./build.sh:/app/build.sh
      - ./.air.toml:/app/.air.toml
      - ./cmd:/app/cmd
      - ./src:/app/src
      - ./public:/app/public
      - ./templates:/app/templates
    ports:
      - 8079:8079
